---
apiVersion: v1
kind: Secret
metadata:
  name: flux-system
  namespace: flux-system
stringData:
  identity: |
    -----BEGIN PRIVATE KEY-----
    MIG2AgEAMBAGByqGSM49AgEGBSuBBAAiBIGeMIGbAgEBBDC43uWaB/iDI9NSIUhJ
    9/YQVmdx3eDc76JxDFTcMMhXTUwRFvRXjnc/2/S5vAF/ysehZANiAASdSS8Xz+88
    fUUTqBI91wtYY/Fa5Xq2wJjnA88hfz7RI6tNxwcvGNdnVbYmjYKirKuumCu/cT4c
    VL5NWbFGBBH8C0m0GnZn/4t4WoTa+EZZDVLyJP+WyBSTODtM3BpAo4w=
    -----END PRIVATE KEY-----
  identity.pub: |
    ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBJ1JLxfP7zx9RROoEj3XC1hj8VrlerbAmOcDzyF/PtEjq03HBy8Y12dVtiaNgqKsq66YK79xPhxUvk1ZsUYEEfwLSbQadmf/i3hahNr4RlkNUvIk/5bIFJM4O0zcGkCjjA==
  known_hosts: 192.168.55.220 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBILS6t/WSYUs4Y/NHRav1U4v+AraY4SdpiHNaJigQYu2M1HJWRBra99ZM7Y23Tt5jwz5Ifj05qF4HeY4i2SQK28=
