[env]
CLUSTER = "nibbler"
GIT_REPO_URL = {
  required = "URL to this repository. Can be local reachable only."
}
KIND_COMMAND="kind"
KUBECONFIG = "{{env.HOME}}/.kube/clusters/{{env.CLUSTER}}"

[hooks]
enter = 'echo "☸️ Active cluster: $CLUSTER"'

[tasks.apply-custom-config]
run = [
  "kubectl apply -k custom-config/{{env.CLUSTER}}/kustomize",
  "kubectl apply -f custom-config/{{env.CLUSTER}}/manifests",
]

[tasks.install-cluster]
run = [
  "touch {{env.KUBECONFIG}}",
  { task = "install-kind" },
  { task = "install-cilium" },
  { task = "install-flux-operator" },
  'echo "✅ cluster $CLUSTER installed."',
  "echo \"🔧 Run the 'connect-flux-repo' task to finish cluster setup.\"",
]

[tasks.install-kind]
run = "{{env.KIND_COMMAND}} create cluster --config kind/{{env.CLUSTER}}.yaml"

[tasks.uninstall-cluster]
run = "{{env.KIND_COMMAND}} delete cluster --name {{env.CLUSTER}}"
confirm = "⚠️ This will remove your {{env.CLUSTER}} cluster. Continue?"

[tools]
"ubi:controlplaneio-fluxcd/flux-operator" = { version = "0.37.1", matching = "operator_" }
"ubi:envoyproxy/gateway" = { version = "1.6.1", matching = "egctl", exe = "egctl" }
"ubi:komodorio/helm-dashboard" = "2.0.4"
cilium-cli = "0.19.2"
cilium-hubble = "1.18.6"
cmctl = "2.4.0"
flux2 = "2.8.1"
helm = "4.1.1"
kind = "0.31.0"
