[hooks]
enter = "echo '✅ kind-cilium activated'"
leave = "echo '❌ kind-cilium deactivated'"

[env]
KIND_EXPERIMENTAL_PROVIDER = "nerdctl"
KUBECONFIG = "{{env.HOME}}/.kube/clusters/cilium"

[tasks.install-cluster]
run = "sudo kind create cluster --config kind.yaml"

[tasks.uninstall-cluster]
run = "sudo kind delete cluster --name cilium"

[tools]
cilium-cli = "0.18.8"
