[env]
CLUSTER = "nibbler"
GIT_REPO_URL = {
  required = "URL to this repository. Can be local reachable only."
}
KIND_COMMAND="kind"
KUBECONFIG = "{{env.HOME}}/.kube/clusters/{{env.CLUSTER}}"

[hooks]
enter = 'echo "☸️ Active cluster: $CLUSTER"'

[tasks.apply-custom-config]
run = [
  "kubectl apply -k custom-config/{{env.CLUSTER}}/kustomize",
  "kubectl apply -f custom-config/{{env.CLUSTER}}/manifests",
]

[tasks.install-cluster]
run = [
  "touch {{env.KUBECONFIG}}",
  { task = "install-kind" },
  { task = "install-prometheus-crds" },
  { task = "install-cilium" },
  { task = "install-flux-operator" },
  'echo "✅ cluster $CLUSTER installed."',
  "echo \"🔧 Run the 'connect-flux-repo' task to finish cluster setup.\"",
]

[tasks.install-kind]
run = "{{env.KIND_COMMAND}} create cluster --config kind/{{env.CLUSTER}}.yaml"

[tasks.uninstall-cluster]
run = "{{env.KIND_COMMAND}} delete cluster --name {{env.CLUSTER}}"
confirm = "⚠️ This will remove your {{env.CLUSTER}} cluster. Continue?"

[tools]
"github:controlplaneio-fluxcd/flux-operator" = { version = "0.58.1", matching = "operator_" }
"github:envoyproxy/gateway" = { version = "1.9.1", matching = "egctl", bin_path = "bin/linux/amd64" }
"github:komodorio/helm-dashboard" = "2.1.3"
cilium-cli = "0.20.0"
cilium-hubble = "1.19.4"
cmctl = "2.5.0"
flux2 = "2.9.4"
helm = "4.2.4"
kind = "0.33.0"
