[env]
KIND_EXPERIMENTAL_PROVIDER = "nerdctl"
KUBECONFIG = "{{env.HOME}}/.kube/clusters/nibbler"

[tasks.install-cluster]
run = [
  { task = "install-kind" },
  { task = "install-cilium" },
  { task = "install-flux" },
  "echo '🏁 cluster installed.'",
]

[tasks.install-kind]
run = "sudo -E kind create cluster --config kind.yaml"

[tasks.uninstall-cluster]
run = "sudo -E kind delete cluster --name nibbler"
confirm = "⚠️ This will remove your cluster. Continue?"

[tools]
"ubi:controlplaneio-fluxcd/flux-operator" = { version = "0.37.1", matching = "operator_" }
"ubi:envoyproxy/gateway" = { version = "1.6.1", matching = "egctl", exe = "egctl" }
"ubi:komodorio/helm-dashboard" = "2.0.4"
cilium-cli = "0.18.9"
cmctl = "2.4.0"
flux2 = "2.7.5"
helm = "4.0.4"
kind = "0.31.0"
