apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: victoria-metrics-system
resources:
  - namespace.yaml
  - flux-ks.yaml
configMapGenerator:
  - name: victoria-metrics-values
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
      labels:
        reconcile.fluxcd.io/watch: Enabled
