---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-echo
spec:
  hostnames:
    - ${hostname:=echo-example.cluster.local}
  parentRefs:
    - name: ${gateway:=envoy-gateway-main}
      namespace: ${gatewayNamespace:=envoy-gateway-system}
      group: gateway.networking.k8s.io
      kind: Gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ${servicePrefix:=echo-envoy-gateway}-1
          kind: Service
          port: ${servicePort1:=5090}
          weight: ${serviceWeight1:=75}
        - name: ${servicePrefix:=echo-envoy-gateway}-2
          kind: Service
          port: ${servicePort2:=6090}
          weight: ${serviceWeight2:=25}
    - matches:
        - path:
            type: PathPrefix
            value: /gw2
      backendRefs:
        - name: ${servicePrefix:=echo-envoy-gateway}-2
          port: ${servicePort2:=6090}
