---
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: envoy-gateway-${instance}-pool
spec:
  blocks:
    # Configure unused IPs from the kind subnet on the host
    # Check with: `nerdctl network inspect kind`
    - cidr: ${cidrIPPool}
