---
config:
  gatewayAPI:
    enabled: true
    enableListenerSet: true
  featureGates:
    ListenerSets: true
crds:
  enabled: true
global:
  leaderElection:
    namespace: cert-manager-system
prometheus:
  enabled: false
