kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: nibbler
nodes:
  - role: control-plane
    image: &image kindest/node:v1.37.0@sha256:a1ed56cfb0e7b93589bdf97c8cd566405a265939e3620fc4f5de89adff580ae5
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        controllerManager:
          extraArgs:
            bind-address: "0.0.0.0"
        scheduler:
          extraArgs:
            bind-address: "0.0.0.0"
        etcd:
          local:
            extraArgs:
              listen-metrics-urls: "http://0.0.0.0:2381"
  - role: worker
    image: *image
  - role: worker
    image: *image
  - role: worker
    image: *image
  - role: worker
    image: *image
networking:
  disableDefaultCNI: true
  kubeProxyMode: "none"
