---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system-web-ui-gtw
  namespace: flux-system
spec:
  interval: 15m
  targetNamespace: flux-system
  dependsOn:
    - name: envoy-gateway-system
      namespace: envoy-gateway-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "/apps/flux-web-ui-gtw"
  prune: true
