apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: envoy-gateway-system
resources:
  - namespace.yaml
  - config-redis.yaml
  - app-redis.yaml
  - app-envoy-gateway-system.yaml
configMapGenerator:
  - name: envoy-gateway-values
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
      labels:
        reconcile.fluxcd.io/watch: Enabled
