---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisSentinel
metadata:
  name: redis-${instance}
spec:
  clusterSize: 3
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
  redisSentinelConfig:
    # Could not perform a stable failover.
    #
    # Steps to reproduce:
    # 1. Delete master pod
    # 2. Watch sentinel service logs
    # 3. Verify another node is promoted
    # 4. Verify `role:master` on new redis pod with `INFO REPLICATION`
    # 5. Fail: ´redis-role=master` label will not be added to the promoted pod
    # 6. Fail: redis master service has no Endpoints to select
    #
    # See https://github.com/OT-CONTAINER-KIT/redis-operator/issues/1544
    redisReplicationName: redis-${instance}
    masterGroupName: redis-${instance}
    downAfterMilliseconds: "1000"
    failoverTimeout: "3000"
  kubernetesConfig:
    image: quay.io/opstree/redis-sentinel:v8.4.0
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
