---
k8sServiceHost: "nibbler-control-plane"
k8sServicePort: "6443"
kubeProxyReplacement: true
ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - 10.244.0.0/16
l2announcements:
  enabled: true
gatewayAPI:
  enabled: true
nodePort:
  enabled: true
hubble:
  relay:
    enabled: false
  ui:
    enabled: false
