---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gw-internal
  namespace: echo-example
spec:
  gatewayClassName: cilium
  # addresses:
  #   - type: "IPAddress" # fake
  #     value: "172.10.10.10"
  listeners:
  - protocol: HTTP
    port: 9090
    name: http-gw
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-echo
  namespace: echo-example
spec:
  parentRefs:
  - name: gw-internal
    namespace: echo-example
  hostnames:
  - echo.cluster.local
  - echo
  rules:
  # Both filters do not work at the same time.
  # This filter wins.
  - filters:
    - type: ResponseHeaderModifier
      responseHeaderModifier:
        add:
        - name: "Cache-Control"
          value: "max-age=60, public"
        - name: X-Powered-By
          value: Bash
        # Also not possible.
        # Probably because it is set by envoy.
        remove:
        - server
  - backendRefs:
    - name: echo-1
      port: 8080
      weight: 70
      filters:
      - type: ResponseHeaderModifier
        responseHeaderModifier:
          add:
          - name: X-Powered-By
            value: PHP
    - name: echo-2
      port: 8090
      weight: 30
