---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 15m
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "/infra/controllers/cilium"
  prune: false
  wait: false
