---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  # This instance is non-persistent.
  # Add `redis.spec.storage` to be persistent.
  name: redis-${instance}
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v8.8.2
    resources:
      requests:
        cpu: 100m
        memory: 32Mi
      limits:
        cpu: 200m
        memory: 96Mi
  redisConfig:
    additionalRedisConfig: redis-${instance}-config
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
