---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: global-defaults
  namespace: envoy-gateway-system
spec:
  # [TargetSelector](https://gateway.envoyproxy.io/v1.6/api/extension_types/#targetselector) did
  # not work for me. Configured in the same and the `envoy-gateway-system` namespace.
  targetRefs:
    - kind: Gateway
      group: gateway.networking.k8s.io
      name: envoy-gateway
  # Custom headers
  headers:
    lateResponseHeaders:
      add:
        - name: "x-custom-header"
          value: "true"
      set:
        - name: "server"
          value: "Microsoft-IIS/8.0"
  # Enable HTTP/3
  # Not sure if this is working. Tested with `curl --http3(-only)`.
  # Got a `alt-svc: h3=":443"; ma=86400` response header
  # See https://github.com/envoyproxy/gateway/issues/5005
  http3: {}
