---
apiVersion: v1
kind: Namespace
metadata:
  name: &name nginx-example
  labels:
    kubernetes.io/metadata.name: *name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name nginx-example
  namespace: *name
spec:
  selector:
    matchLabels:
      app: *name
  replicas: 2
  template:
    metadata:
      labels:
        app: *name
    spec:
      containers:
      - name: nginx
        image: nginx:1.28.0-alpine
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: &name nginx-example
  namespace: *name
spec:
  selector:
    app: *name
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
