---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
spec:
  interval: 5m
  timeout: 15m
  chart:
    spec:
      chart: victoria-metrics-operator
      version: "0.63.1"
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
      interval: 1h
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: ConfigMap
      name: victoria-metrics-values
      valuesKey: values.yaml
