---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-operator
spec:
  chart:
    spec:
      chart: redis-operator
      version: ${quote:="}${chartVersion:=0.22.2}${quote:="}
      sourceRef:
        kind: HelmRepository
        name: redis-operator
  driftDetection:
    mode: enabled
  interval: 15m
  timeout: 5m
