---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-bench
  namespace: flux-system
spec:
  interval: 15m
  targetNamespace: kube-bench
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "/apps/kube-bench"
  prune: true
  postBuild:
    substitute:
      schedule: "*/5 * * * *"
      commandArgs: "['-D', '/opt/kube-bench/cfg', '--version', '1.35']"
