---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: echo-cilium-gateway-2
  namespace: flux-system
spec:
  interval: 15m
  targetNamespace: echo-cilium-gatway
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "/apps/echo"
  prune: true
  postBuild:
    substitute:
      instance: "echo-cilium-gateway-2"
      replicas: "3"
      port: "8090"
