---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: echo-envoy-gtw
  namespace: flux-system
spec:
  interval: 15m
  targetNamespace: echo-envoy-gateway
  dependsOn:
    - name: envoy-gateway-system
      namespace: envoy-gateway-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "/apps/echo-gtw"
  prune: true
  postBuild:
    substitute:
      var_substitution_enabled: "true"
    substituteFrom:
      - kind: ConfigMap
        name: custom-vars-echo-envoy-gtw
        optional: true
