#!/usr/bin/env bash

helm repo add --force-update cilium https://helm.cilium.io/
helm upgrade --install cilium cilium/cilium \
  --version 1.19.1 \
  --namespace kube-system \
  --values "clusters/${CLUSTER}/infra/controllers/cilium/values.yaml"

echo >&2
echo "Waiting for Cilium to be ready:" >&2
cilium status --wait

echo >&2
echo "Installing Gateway API:" >&2
kubectl apply --server-side -f infra/controllers/gateway-api/crd-gateway-api.yaml
