#!/usr/bin/env bash

helm upgrade --install flux-operator oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator \
  --namespace flux-system \
  --create-namespace \
  --wait

kubectl apply -f clusters/nibbler/infra/configs/flux/

echo "Check the status with:" >&2
echo >&2
echo "  kubectl -n flux-system port-forward svc/flux-operator 9080:9080" >&2
echo "  xdg-open localhost:9080" >&2
