#!/usr/bin/env bash

helm repo add --force-update cilium https://helm.cilium.io/
helm upgrade --install cilium cilium/cilium \
  --version 1.18.5 \
  --namespace kube-system \
  --values clusters/nibbler/infra/cilium/values.yaml
