---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: kube-system
spec:
  interval: 15m
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "/apps/kube-prometheus-stack"
  prune: true
